[project]
name = "recommend"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "requests>=2.32.4",
    "flask>=3.0.0",
    "psycopg>=3.1.0",
    "redis>=5.0.0",
]
