// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Feed struct {
	ID          int32          `json:"id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Link        string         `json:"link"`
	RsshubRoute string         `json:"rsshub_route"`
	FeedUrl     string         `json:"feed_url"`
	LastUpdated sql.NullTime   `json:"last_updated"`
	IsActive    sql.NullBool   `json:"is_active"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type FeedItem struct {
	ID     int32         `json:"id"`
	FeedID sql.NullInt32 `json:"feed_id"`
	// 文章标题（支持分词标签）
	Title string `json:"title"`
	// 文章描述（支持分词标签）
	Description sql.NullString `json:"description"`
	// 文章内容（支持分词标签）
	Content sql.NullString `json:"content"`
	Link    string         `json:"link"`
	Guid    string         `json:"guid"`
	Author  sql.NullString `json:"author"`
	// 关键词数组（通过分词算法提取）
	Keywords    []string     `json:"keywords"`
	PublishedAt sql.NullTime `json:"published_at"`
	CreatedAt   sql.NullTime `json:"created_at"`
}

type InviteCode struct {
	ID                 uuid.UUID     `json:"id"`
	Email              string        `json:"email"`
	Code               string        `json:"code"`
	IsUsed             sql.NullBool  `json:"is_used"`
	HasRecommend       sql.NullBool  `json:"has_recommend"`
	HasMoreInformation sql.NullBool  `json:"has_more_information"`
	CreatedAt          sql.NullTime  `json:"created_at"`
	Count              sql.NullInt32 `json:"count"`
}

type ReadingSession struct {
	ID         uuid.UUID             `json:"id"`
	UserID     uuid.UUID             `json:"user_id"`
	ArticleID  string                `json:"article_id"`
	StartTime  sql.NullTime          `json:"start_time"`
	EndTime    sql.NullTime          `json:"end_time"`
	DeviceInfo pqtype.NullRawMessage `json:"device_info"`
}

type User struct {
	ID                  uuid.UUID      `json:"id"`
	Email               string         `json:"email"`
	Gender              sql.NullString `json:"gender"`
	Age                 sql.NullInt32  `json:"age"`
	DateOfBirth         sql.NullTime   `json:"date_of_birth"`
	EducationLevel      sql.NullString `json:"education_level"`
	Residence           sql.NullString `json:"residence"`
	WeeklyReadingHours  sql.NullInt32  `json:"weekly_reading_hours"`
	PrimaryNewsPlatform sql.NullString `json:"primary_news_platform"`
	IsActiveSearcher    sql.NullBool   `json:"is_active_searcher"`
	IsColorblind        sql.NullBool   `json:"is_colorblind"`
	VisionStatus        sql.NullString `json:"vision_status"`
	IsVisionCorrected   sql.NullBool   `json:"is_vision_corrected"`
	CreatedAt           sql.NullTime   `json:"created_at"`
}

type UserSession struct {
	ID            uuid.UUID    `json:"id"`
	UserID        uuid.UUID    `json:"user_id"`
	StartTime     sql.NullTime `json:"start_time"`
	LastHeartbeat sql.NullTime `json:"last_heartbeat"`
	IsActive      sql.NullBool `json:"is_active"`
	CreatedDate   sql.NullTime `json:"created_date"`
	EndTime       sql.NullTime `json:"end_time"`
}
