// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Feed struct {
	ID          int32          `json:"id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Link        string         `json:"link"`
	RsshubRoute string         `json:"rsshub_route"`
	FeedUrl     string         `json:"feed_url"`
	LastUpdated sql.NullTime   `json:"last_updated"`
	IsActive    sql.NullBool   `json:"is_active"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type FeedItem struct {
	ID          int32          `json:"id"`
	FeedID      sql.NullInt32  `json:"feed_id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Content     sql.NullString `json:"content"`
	Link        string         `json:"link"`
	Guid        string         `json:"guid"`
	Author      sql.NullString `json:"author"`
	PublishedAt sql.NullTime   `json:"published_at"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type InviteCode struct {
	ID                 int32         `json:"id"`
	Code               string        `json:"code"`
	IsUsed             sql.NullBool  `json:"is_used"`
	UsedByUserID       sql.NullInt32 `json:"used_by_user_id"`
	HasRecommend       sql.NullBool  `json:"has_recommend"`
	HasMoreInformation sql.NullBool  `json:"has_more_information"`
	CreatedAt          sql.NullTime  `json:"created_at"`
}

type ReadingSession struct {
	ID                uuid.UUID             `json:"id"`
	UserID            int32                 `json:"user_id"`
	ArticleID         int32                 `json:"article_id"`
	StartTime         sql.NullTime          `json:"start_time"`
	EndTime           sql.NullTime          `json:"end_time"`
	DeviceInfo        pqtype.NullRawMessage `json:"device_info"`
	OssFilePath       sql.NullString        `json:"oss_file_path"`
	DataSize          sql.NullInt64         `json:"data_size"`
	EventCount        sql.NullInt32         `json:"event_count"`
	SessionDurationMs sql.NullInt64         `json:"session_duration_ms"`
}

type User struct {
	ID                  int32          `json:"id"`
	Email               string         `json:"email"`
	Gender              sql.NullString `json:"gender"`
	Age                 sql.NullInt32  `json:"age"`
	DateOfBirth         sql.NullTime   `json:"date_of_birth"`
	EducationLevel      sql.NullString `json:"education_level"`
	Residence           sql.NullString `json:"residence"`
	WeeklyReadingHours  sql.NullInt32  `json:"weekly_reading_hours"`
	PrimaryNewsPlatform sql.NullString `json:"primary_news_platform"`
	IsActiveSearcher    sql.NullBool   `json:"is_active_searcher"`
	IsColorblind        sql.NullBool   `json:"is_colorblind"`
	VisionStatus        sql.NullString `json:"vision_status"`
	IsVisionCorrected   sql.NullBool   `json:"is_vision_corrected"`
	InviteCodeID        int32          `json:"invite_code_id"`
	CreatedAt           sql.NullTime   `json:"created_at"`
}
