// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user_sessions.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUserSession = `-- name: CreateUserSession :exec
INSERT INTO user_sessions (
    id, user_id, start_time, last_heartbeat, is_active
) VALUES (
    $1, $2, $3, $4, $5
)
`

type CreateUserSessionParams struct {
	ID            uuid.UUID    `json:"id"`
	UserID        uuid.UUID    `json:"user_id"`
	StartTime     sql.NullTime `json:"start_time"`
	LastHeartbeat sql.NullTime `json:"last_heartbeat"`
	IsActive      sql.NullBool `json:"is_active"`
}

// 创建新的用户会话
func (q *Queries) CreateUserSession(ctx context.Context, arg CreateUserSessionParams) error {
	_, err := q.db.ExecContext(ctx, createUserSession,
		arg.ID,
		arg.UserID,
		arg.StartTime,
		arg.LastHeartbeat,
		arg.IsActive,
	)
	return err
}
