[project]
name = "split"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "flask>=3.1.1",
    "jieba>=0.42.1",
    "psycopg>=3.2.9",
    "regex>=2024.11.6",
]
